from utility import *

eg("the", "show options", oo)
eg("rand", "demo random number generation", randFunc)
eg("some", "demo of reservoir sampling", someFunc)
eg("nums","demo of NUM", numFunc)
eg("syms","demo SYMS", symFunc)
eg("csv", "reading csv files", csvFunc)
eg("data", "showing data sets", dataFunc)
eg("cliffs", "stats tests", cliffsFunc)
# eg("copy", "check copy", copyFunc)
# eg("num", "check nums", numFunc)
# eg("repcols", "checking repcols", repColsFunc)
# eg("synonyms","checking repcols cluster", synonymsFunc)
# eg("reprows","checking reprows", reprowsFunc)
